## Combine, filter and save XRD data

In [1]:
#loads and combines all .csv files for XRD data into one file

import pandas as pd
import glob
import os

pd.set_option('display.max_columns', None)

files = glob.glob('raw_data/rcsb_pdb_custom_report_*.csv')

if(os.path.exists('raw_data/XRD_combined.csv') and os.path.isfile('raw_data/XRD_combined.csv')):
    os.remove('raw_data/XRD_combined.csv')
else:
    pass

for i in files:
    df = pd.read_csv(i, header=1)
    df = df.fillna(method='ffill')
    df = df[df['Experimental Method'].isin(['X-RAY DIFFRACTION'])]
    df = df.drop(['EM Resolution (Å)', 'Unnamed: 22', 'Ligand','Entry Id (Polymer Entity Identifiers)',
                  'Molecular Weight per Deposited Model'], axis=1)
    df.to_csv('raw_data/XRD_combined.csv', mode='a')

In [2]:
#filters and cleans dataframe for further use
#second dataframe is then created and saved which does not contain any duplicates based on 'Entry ID'

data = pd.read_csv('raw_data/XRD_combined.csv', encoding = 'utf8')
data = data.drop(['Unnamed: 0'], axis=1)

data_1 = data.drop_duplicates(subset=['Entry ID'])

if(os.path.exists('raw_data/XRD_combined_noduplicates.csv') and os.path.isfile('raw_data/XRD_combined_noduplicates.csv')):
    os.remove('raw_data/XRD_combined_noduplicates.csv')
    data_1.to_csv('raw_data/XRD_combined_noduplicates.csv', mode='a')
else:
    data_1.to_csv('raw_data/XRD_combined_noduplicates.csv', mode='a')

### Initial data processing for analysis

In [3]:
#basic column type definitions and changes to numeric dtype

float_columns = ['Matthews Coefficient','Percent Solvent Content','pH','Temp (K)',
                'Resolution (Å)','High Resolution Limit','Entity ID'] 
str_columns = ['Entry ID','Experimental Method','Crystallization Method','Crystal Growth Procedure','DOI','PDB ID',
              'Structure Title','Sequence','Source Organism','Gene Name']

for i in float_columns:
    data[i] = pd.to_numeric(data[i], errors='coerce')

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83968 entries, 0 to 83967
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Entry ID                  83968 non-null  object
 1   Experimental Method       83968 non-null  object
 2   Matthews Coefficient      83944 non-null  float64
 3   Percent Solvent Content   83944 non-null  float64
 4   Crystallization Method    83963 non-null  object
 5   pH                        83867 non-null  float64
 6   Crystal Growth Procedure  83965 non-null  object
 7   Temp (K)                  83939 non-null  float64
 8   DOI                       83659 non-null  object
 9   PDB ID                    83968 non-null  object
 10  Resolution (Å)            83944 non-null  float64
 11  High Resolution Limit     83944 non-null  float64
 12  Structure Title           83968 non-null  object
 13  Sequence                  83968 non-null  object
 14  Source Organism           83968 non-null  object
 15  Gene Name                 83968 non-null  object
 16  Macromolecule Name        83968 non-null  object
 17  Entity ID                 83944 non-null  float64
dtypes: float64(7), object(11)
memory usage: 11.5+ MB

In [5]:
data.describe()

,Matthews Coefficient,Percent Solvent Content,pH,Temp (K),Resolution (Å),High Resolution Limit,Entity ID
count,83944.000000,83944.000000,83867.000000,83939.000000,83944.000000,83944.000000,83944.000000
mean,2.736365,52.653792,6.831990,290.311884,2.281837,2.281837,1.695595
std,0.706073,9.873950,1.175493,7.140212,0.671128,0.671128,2.214842
min,0.410000,0.360000,1.000000,100.000000,0.660000,0.660000,1.000000
25%,2.270000,45.710000,6.000000,290.000000,1.820000,1.820000,1.000000
50%,2.570000,52.120000,7.000000,293.000000,2.200000,2.200000,1.000000
75%,3.000000,59.010000,7.500000,294.000000,2.683250,2.683250,2.000000
max,13.890000,90.010000,11.100000,323.000000,9.700000,9.700000,89.000000